username:
password:

positions:
  - Software Engineer
  - Javascript Engineer
  - Full Stack Engineer
  - Frontend Engineer
  - Software Developer
  - Javascript Developer
  - Typescript Engineer
  - Typescript Developer
  - React Engineer
  - React Developer

locations:
  - Remote
  - Los Angeles Metropolitan Area
  - San Francisco Bay Area
  - California, United States
  - United States
# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo

output_filename:
  - output.csv
# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
